import type { PrismaField, PrismaModel, PrismaSchema, ScenarioPack, ScenarioRecord } from "../prisma/types.js";
import { camelCaseModel } from "../util/case.js";

export function renderPrismaSeed(pack: ScenarioPack, schema: PrismaSchema): string {
  const modelByName = new Map(schema.models.map((model) => [model.name, model]));
  const lines: string[] = [
    "import { PrismaClient } from \"@prisma/client\";",
    "",
    "const prisma = new PrismaClient();",
    "",
    "async function main() {",
    `  // Generated by ScenarioSeed: ${pack.name}`
  ];

  for (const scenario of pack.scenarios) {
    lines.push("", `  // Scenario: ${scenario.title} (${scenario.key})`);
    const scenarioRecords = pack.records.filter((record) => record.scenario === scenario.key);
    for (const record of scenarioRecords) {
      const model = modelByName.get(record.model);
      if (!model) {
        continue;
      }
      lines.push(...renderRecord(record, model).map((line) => `  ${line}`));
    }
  }

  lines.push(
    "}",
    "",
    "main()",
    "  .then(async () => {",
    "    await prisma.$disconnect();",
    "  })",
    "  .catch(async (error) => {",
    "    console.error(error);",
    "    await prisma.$disconnect();",
    "    process.exit(1);",
    "  });",
    ""
  );

  return lines.join("\n");
}

function renderRecord(record: ScenarioRecord, model: PrismaModel): string[] {
  const delegate = camelCaseModel(model.name);
  const uniqueField = findUniqueField(model, record.data);
  const create = renderObject(record.data, model, 2);

  if (!uniqueField) {
    return [`await prisma.${delegate}.create({`, `  data: ${create}`, "});"];
  }

  const where = renderObject({ [uniqueField.name]: record.data[uniqueField.name] }, model, 2);
  return [
    `await prisma.${delegate}.upsert({`,
    `  where: ${where},`,
    "  update: {},",
    `  create: ${create}`,
    "});"
  ];
}

function findUniqueField(model: PrismaModel, data: Record<string, unknown>): PrismaField | undefined {
  return model.fields.find((field) => (field.isId || field.isUnique) && data[field.name] !== undefined);
}

function renderObject(value: Record<string, unknown>, model: PrismaModel, indentLevel: number): string {
  const indent = "  ".repeat(indentLevel);
  const childIndent = "  ".repeat(indentLevel + 1);
  const entries = Object.entries(value);
  if (entries.length === 0) {
    return "{}";
  }

  const lines = ["{"];
  for (const [key, item] of entries) {
    const field = model.fields.find((candidate) => candidate.name === key);
    lines.push(`${childIndent}${key}: ${renderValue(item, field)},`);
  }
  lines.push(`${indent}}`);
  return lines.join("\n");
}

function renderValue(value: unknown, field?: PrismaField): string {
  if (field?.type === "DateTime" && typeof value === "string") {
    return `new Date(${JSON.stringify(value)})`;
  }
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value === null) {
    return "null";
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => renderValue(item)).join(", ")}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) {
      return "{}";
    }
    return `{ ${entries.map(([key, item]) => `${key}: ${renderValue(item)}`).join(", ")} }`;
  }
  return "undefined";
}
